sudo: required
dist: trusty
os:
  - linux
  - osx
osx_image: xcode7.3
language: go
go:
  - 1.6
install: true
services:
  - docker
before_install:
  - if [ "$TRAVIS_OS_NAME" == 'linux' ]; then
      export DEBIAN_FRONTEND=noninteractive;
      sudo apt-get update;
      sudo apt-get install -q -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" fuse;
    else
      cd $GOPATH/src/github.com/keybase &&
      echo "Cloning client" &&
      git clone https://github.com/keybase/client.git &&
      cd client/osx/Fuse &&
      echo "Installing OSXFuse" &&
      ./install.sh &&
      echo "OSXFuse installed";
      cd $GOPATH/src/github.com/keybase/kbfs;
    fi
  - if [ "$TRAVIS_OS_NAME" == 'linux' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      sudo apt-get install -q -y --force-yes -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" docker-engine &&
      docker login -e $CI_EMAIL -u $DOCKER_USER -p $DOCKER_PASS &&
      docker pull $DOCKER_USER/kbclient &&
      docker tag $DOCKER_USER/kbclient kbclient;
    fi
script:
  - go get -u github.com/golang/lint/golint
  - go install github.com/golang/lint/golint
  - lint=$(make -s lint)
    echo 2>&1 "$lint"
    [ -z "$lint" -o "$lint" = "Lint-free!" ]
  - go vet $(go list ./... 2>/dev/null | grep -v /vendor/)
  - go install github.com/keybase/kbfs/...
  # Run libkbfs tests with an in-memory bserver and mdserver, and run all other
  # tests with the tempdir bserver and mdserver.
  - cd libkbfs && go test -i && go test -race -c && ./libkbfs.test -test.timeout 2m
  - env KEYBASE_TEST_BSERVER_ADDR=tempdir ./libkbfs.test -test.timeout 2m
  - cd ../libfuse && go test -i && go test -c && env KEYBASE_TEST_BSERVER_ADDR=tempdir KEYBASE_TEST_MDSERVER_ADDR=tempdir ./libfuse.test -test.timeout 2m
  - cd ../test
  - go test -i -tags fuse && go test -race -c && env KEYBASE_TEST_BSERVER_ADDR=tempdir KEYBASE_TEST_MDSERVER_ADDR=tempdir ./test.test -test.timeout 7m
  - go test -c -tags fuse && env KEYBASE_TEST_BSERVER_ADDR=tempdir KEYBASE_TEST_MDSERVER_ADDR=tempdir ./test.test -test.timeout 7m
after_success:
  - if [ "$TRAVIS_OS_NAME" == 'linux' ] && [ "$TRAVIS_PULL_REQUEST" == 'false' ]; then
      cp $GOPATH/bin/kbfsfuse $GOPATH/src/github.com/keybase/kbfs/kbfsfuse/kbfsfuse &&
      docker build -t $DOCKER_USER/kbfsfuse --build-arg KEYBASE_TEST_ROOT_CERT_PEM_B64="$KEYBASE_TEST_ROOT_CERT_PEM_B64" $GOPATH/src/github.com/keybase/kbfs/kbfsfuse &&
      docker push $DOCKER_USER/kbfsfuse;
    fi
notifications:
  slack: keybase:WKlhs55Mb4am4obv1rNRg8P0
branches:
  only:
    - master
