environment:
  global:
    GOPATH: c:\work\
    KEYBASE_SERVER_URI: https://ci1.keybase.io
    CGO_ENABLED: 1
    GOARCH: 386
    CC: c:\MinGW\bin\gcc
    CPATH: C:\MinGW\include;C:\MinGW\include\ddk
    GOVERSION: 1.6.2

install:
  - systeminfo | findstr /C:"OS"
  - appveyor DownloadFile https://storage.googleapis.com/golang/go%GOVERSION%.windows-amd64.zip
  - ps: rmdir C:\go -Force -Recurse -Confirm:$false
  - 7z x go%GOVERSION%.windows-amd64.zip -o"C:\" -y > nul
  - set Path=c:\go\bin;%Path%
  - appveyor DownloadFile https://github.com/dokan-dev/dokany/releases/download/v0.8.0/dokan.zip
  - 7z x dokan.zip -o"C:\dokan" -y -aoa > nul
  - copy C:\dokan\x64\Win8.1Release\sys\dokan.sys C:\windows\system32\drivers\
  - pushd C:\dokan\Win32\Release
  - copy dokan.dll C:\windows\syswow64\
  - Bcdedit.exe -set TESTSIGNING ON
  - ps: Restart-Computer -Force
  - ps: Start-Sleep -s 10
  - cd C:\dokan\Win32\Release
  - dokanctl /i a

# clone directory
clone_folder: c:\work\src\github.com\keybase\kbfs

#---------------------------------#
#       build configuration       #
#---------------------------------#

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform: x64
os: Visual Studio 2015

# scripts to run before build
before_build:

# scripts to run after build
after_build:

# to run your custom scripts instead of automatic MSBuild
build_script:
  - SET PATH=%PATH%;c:\MinGW\bin
  - git clone git@github.com:keybase/kbfs-binary-windows.git c:\work\src\github.com\keybase\kbfs-binary-windows
  - cd c:\work\src\github.com\keybase\kbfs-binary-windows
# throwaway branch to check out locally at a specific tag  
  - git checkout -b dokan-v0.8.0 dokan-v0.8.0
  - copy dokan\dokan.lib ..\kbfs\dokan
  - cd ..\kbfs\dokan
  - go test -i
  - go test -c
  - cd ..\libdokan
  - go test -i
  - go test -c
  - cd ..\kbfsdokan
  - go build
  - cd ..\test
  - go test -i
  - cd ..
# Eventually there will be more tests, but let's just start with these for now
#  - go list ./... | find /V "vendor" > testlist.txt
  - echo github.com/keybase/kbfs/libkbfs > testlist.txt
  - echo github.com/keybase/kbfs/libdokan >> testlist.txt
  - echo github.com/keybase/kbfs/test >> testlist.txt
# TODO: Run the below tests with env KEYBASE_TEST_BSERVER_ADDR=tempdir.
  - for /f %%i in (testlist.txt) do (appveyor AddTest %%i -Outcome Running -Framework gotest -Filename %%i & go test -timeout 5m %%i && appveyor UpdateTest %%i -Outcome Passed -Framework gotest -Filename %%i -Duration 0) || (appveyor UpdateTest %%i -Outcome Failed -Framework gotest -Filename %%i -Duration 0 & exit /b 1) 
  - cd test && go test -tags dokan

# to disable automatic builds
#build: off

# to run your custom scripts instead of automatic tests
test_script:

# only run on pull requests and pushes to master
branches:
    only:
        - master
