# -----------------------------------------------------------------------------
#
#   REMINDER: If you edit this file, you'll most likely also want to edit
#   .circleci/config.yml in the client repository!
#
# -----------------------------------------------------------------------------
version: 2
jobs:
  build:
    working_directory: ~/go-path/src/github.com/keybase/kbfs
    parallelism: 1

    docker:
    - image: keybaseprivate/circleci-kbfs@sha256:6e95999341a551ca9d175f497abc6f99e42583d977e26489471a86895327cd28
      command: /sbin/init

    steps:
    # Get gobuild.sh and make it executable.
    # TODO: Change akalin/gobuild-oot to master.
    - run: wget https://raw.githubusercontent.com/keybase/client/akalin/gobuild-oot/shared/react-native/gobuild.sh -O /tmp/gobuild.sh
    - run: chmod a+x /tmp/gobuild.sh

    ##
    ## Build.
    ##

    - checkout

    # TODO: Investigate whether we can do some caching to speed up
    # this step, e.g. of /tmp/go-android/pkg.
    - run:
        environment:
          LOCAL_CLIENT: 0
          LOCAL_KBFS: 1
          KEYBASE_BUILD: kbfsci
          DEST_DIR: /tmp
        command: /tmp/gobuild.sh android

    - run: ls -la /tmp/keybaselib.aar
